<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_nstoryradford.eduThu Mar 18 2021Method _7d05a2</name>
   <tag></tag>
   <elementGuidId>7e1bb404-252f-4a14-8403-b5bc1eb04ec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logArea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logArea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logArea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> nstory@radford.eduThu Mar 18 2021Method: OnlineRent: $500.00Additional Fees: $150PayPal Fees: $19.80Total: $669.80Wed Mar 17 2021Method: OnlineRent: $0.00Additional Fees: $34PayPal Fees: $1.32Total: $35.32Sun Mar 14 2021Method: OnlineRent: $1000.00Additional Fees: $1357PayPal Fees: $71.01Total: $2428.01Sun Mar 14 2021Method: OnlineRent: $1000.00Additional Fees: $334PayPal Fees: $40.32Total: $1374.32Wed Mar 10 2021Method: Manually EnteredTotal: $123123*Any fees are included in total. Check fee status  here. Wed Mar 10 2021Method: Manually EnteredTotal: $1005*Any fees are included in total. Check fee status  here. Wed Mar 10 2021Method: OnlineRent: $1000.00Additional Fees: $undefinedPayPal Fees: $30.30Total: $1030.30 jbradley46@radford.eduThere is no payment history for this user test1@test.comThu Mar 18 2021Method: Manually EnteredTotal: $1000*Any fees are included in total. Check fee status  here. Wed Mar 17 2021Method: Manually EnteredTotal: $1000*Any fees are included in total. Check fee status  here.  test123@radford.eduThere is no payment history for this user test321@gmail.comThere is no payment history for this user</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logArea&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='logArea']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-container']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment History'])[2]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign-Out'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div</value>
   </webElementXpaths>
</WebElementEntity>
